version: ~> 1.0
language: node_js
os:
 - linux
import:
 - ljharb/travis-ci:node/minors/gte_12.yml
 - ljharb/travis-ci:node/pretest.yml
 - ljharb/travis-ci:node/posttest.yml
matrix:
  include:
    - node_js: "10.22"
    - node_js: "10.21"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.20"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.19"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.18"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.17"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.16"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.15"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.14"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.13"
      env: TEST=true ALLOW_FAILURE=true
    - node_js: "10.12"
      env: TEST=true ALLOW_FAILURE=true

